### ISSUE TITLE
TdxHq_GetSecurityQuotes

### ISSUE THREAD

**Issue by hanwenzh** [st0rmman/tdxhq#1]
TdxHq_GetSecurityQuotes 编译错误, 
if((Category< 4) || Category==7 || Category==8 ) //这里 Category 未定义

**Comment by st0rmman** [comment]
删除函数TdxHq_GetSecurityQuotes及定义

**Comment by hanwenzh** [comment]
还得用这个函数呢？

**Comment by st0rmman** [comment]
没计划更新这个函数，有点鸡肋。

**Comment by hackdiy** [comment]
老大，怎样获取实时5档数据啊？
