### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by imaqqqq** [st0rmman/tdxhq#2]
（1）TdxHq_GetSecurityQuotes 编译错误。
我按照前面一个Issue的回答删除了函数TdxHq_GetSecurityQuotes及定义。
请问：如果删除了这个函数，用什么函数得到行情数据？
（2）我安装了boost和zlib，但link的时候还是找不到zlibstatd.lib。
谢谢指点！

**Comment by st0rmman** [comment]
zlibstatd.lib是zlib静态编译的调试库
